databases:
  - name: icf
    databaseName: icf
    user: icf_user
    plan: standard
    diskSizeGB: 10
    region: oregon
    postgresMajorVersion: 15

services:
  - type: web
    name: icf
    runtime: docker
    plan: standard
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: icf
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: icf
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: icf
          property: password
      - key: SERVER_URL
        value: https://icf.onrender.com
      - key: ENCRYPTION_PASSWORD
        generateValue: true
